[package]
name = "liquid_crystal"
authors = ["guilherme Silva Schultz <guilhermeSschultz.contato@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "a library to work with alphanumeric lcd display compatible with the HD44780 controller"
license = "MIT"


[dependencies]
embedded-hal = "0.2.7"
nb = "1"

[toolchain]
channel = "nightly"